version: '3.8'

services:
  document-assistant:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PYTHONPATH=/app/src
      - CONFIG_PATH=/app/config/settings.yaml
    volumes:
      - ../data:/app/data
      - ../config:/app/config
    restart: unless-stopped
    
  # Optional: Add a database service if needed
  # postgres:
  #   image: postgres:15-alpine
  #   environment:
  #     POSTGRES_DB: document_assistant
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: password
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"

# volumes:
#   postgres_data:
