version: '3.8'

services:
  # Main API service - Production ready
  api:
    build:
      context: .
      dockerfile: Dockerfile.production
    image: multi-agent-content-analytics:production
    container_name: multi-agent-content-api
    ports:
      - "8001:8000"
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=INFO
      - ENVIRONMENT=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      # Using named volumes for persistent data
      - content_logs:/app/logs
      - content_cache:/app/cache
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  content_logs:
    name: multi-agent-content-logs
  content_cache:
    name: multi-agent-content-cache
