services:
  agentic-finance-api:
    build:
      context: .
      dockerfile: Dockerfile.production
    container_name: agentic-finance-production
    ports:
      - "8001:8001"
    environment:
      - ENVIRONMENT=production
      - LOG_LEVEL=info
      - PYTHONUNBUFFERED=1
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
      - finance-logs:/app/logs
      - finance-data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - finance-network
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'

  nginx:
    image: nginx:alpine
    container_name: agentic-finance-nginx
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      agentic-finance-api:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - finance-network

networks:
  finance-network:
    driver: bridge

volumes:
  finance-logs:
    driver: local
  finance-data:
    driver: local
