# Vector Database Configuration
vector_db:
  type: "chromadb"
  persist_directory: "./data/vectordb"
  collection_name: "document_embeddings"

# Document Storage Configuration
document_store:
  type: "sqlite"
  database_path: "./data/documents.db"

# Embeddings Configuration
embeddings:
  provider: "sentence_transformers"  # Options: sentence_transformers, openai
  model: "all-MiniLM-L6-v2"  # For sentence_transformers
  # model: "text-embedding-3-small"  # For OpenAI
  api_key: null  # Set your OpenAI API key if using OpenAI
  batch_size: 32

# LLM Configuration
llm:
  provider: "ollama"  # Options: openai, anthropic, ollama
  base_url: "http://localhost:11434"
  model: "llama3"
  temperature: 0.7
  max_tokens: 2048
  
  # OpenAI settings (if using OpenAI)
  # model: "gpt-4o-mini"
  # api_key: "your-api-key-here"
  
  # Anthropic settings (if using Anthropic)
  # model: "claude-3-haiku-20240307"
  # api_key: "your-api-key-here"

# Document Processing Configuration
documents:
  chunk_size: 1000
  chunk_overlap: 200
  min_chunk_size: 100
  max_file_size: "10MB"
  supported_formats:
    - ".txt"
    - ".md"
    - ".pdf"
    - ".docx"
    - ".doc"
    - ".html"
    - ".htm"

# Retrieval Configuration
retrieval:
  default_limit: 5
  max_limit: 20
  similarity_threshold: 0.7

# Server Configuration
server:
  host: "localhost"
  port: 3000
  debug: true
  log_level: "INFO"

# Security Configuration
security:
  max_upload_size: "50MB"
  allowed_origins:
    - "http://localhost:3000"
    - "http://127.0.0.1:3000"
