# Development environment configuration
development:
  database:
    host: localhost
    port: 5432
    name: agentic_finance_dev
    user: postgres
    password: password
  
  redis:
    host: localhost
    port: 6379
    db: 0
  
  api_keys:
    alpha_vantage: ${ALPHA_VANTAGE_API_KEY}
    yahoo_finance: ${YAHOO_FINANCE_API_KEY}
    quandl: ${QUANDL_API_KEY}
  
  agents:
    cleaner:
      max_workers: 2
      timeout: 300
    validator:
      max_workers: 2
      timeout: 180
    analyzer:
      max_workers: 4
      timeout: 600
    visualizer:
      max_workers: 1
      timeout: 300
    recommender:
      max_workers: 2
      timeout: 240

# Production environment configuration
production:
  database:
    host: ${DB_HOST}
    port: ${DB_PORT}
    name: ${DB_NAME}
    user: ${DB_USER}
    password: ${DB_PASSWORD}
  
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    db: 0
    password: ${REDIS_PASSWORD}
  
  api_keys:
    alpha_vantage: ${ALPHA_VANTAGE_API_KEY}
    yahoo_finance: ${YAHOO_FINANCE_API_KEY}
    quandl: ${QUANDL_API_KEY}
  
  agents:
    cleaner:
      max_workers: 4
      timeout: 300
    validator:
      max_workers: 4
      timeout: 180
    analyzer:
      max_workers: 8
      timeout: 600
    visualizer:
      max_workers: 2
      timeout: 300
    recommender:
      max_workers: 4
      timeout: 240

# Data source configurations
data_sources:
  yahoo_finance:
    base_url: "https://query1.finance.yahoo.com"
    rate_limit: 2000  # requests per hour
    timeout: 30
  
  alpha_vantage:
    base_url: "https://www.alphavantage.co/query"
    rate_limit: 500   # requests per day
    timeout: 30
  
  quandl:
    base_url: "https://www.quandl.com/api/v3"
    rate_limit: 50000 # requests per day
    timeout: 30

# Agent-specific configurations
agent_configs:
  data_cleaner:
    default_rules:
      handle_missing: "interpolate"
      outlier_method: "iqr"
      outlier_threshold: 3.0
      validate_business_hours: true
      validate_price_ranges: true
      min_price: 0.01
      max_price_change: 0.5
    
  data_validator:
    validation_rules:
      price_consistency: true
      volume_validation: true
      temporal_consistency: true
      business_rules: true
    quality_threshold: 0.8
  
  financial_analyzer:
    technical_indicators:
      - sma_20
      - sma_50
      - ema_12
      - ema_26
      - rsi
      - macd
      - bollinger_bands
      - stochastic
    risk_metrics:
      - volatility
      - var_95
      - cvar_95
      - max_drawdown
      - sharpe_ratio
      - beta
  
  recommendation_engine:
    strategies:
      - momentum
      - value
      - growth
      - risk_parity
    confidence_threshold: 0.7
    max_recommendations: 10
