version: '3.8'

services:
  # AgenTech Research Hub API
  agentech-api:
    build: .
    container_name: agentech-research-hub
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./.env:/app/.env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - agentech-network

  # Web UI Frontend
  agentech-webui:
    image: nginx:alpine
    container_name: agentech-webui
    ports:
      - "3000:80"
    volumes:
      - ./web-ui:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - agentech-api
    restart: unless-stopped
    networks:
      - agentech-network

  # Redis for caching (optional)
  redis:
    image: redis:alpine
    container_name: agentech-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - agentech-network

volumes:
  redis_data:

networks:
  agentech-network:
    driver: bridge
